#!/usr/bin/env python3
"""
v3.6.27 - 水浒传 109角色提示词全面重写
锁定 98 版 CCTV 电视剧演员特征，去除中文混写/韩式审美，
建立标准化 prompt_en + video_prompts 三方案（肖像/场景/运镜）
"""
import json, os, sys, copy
from datetime import datetime

VISUAL_BIBLE = os.path.expanduser("~/.agentic-os/character_designs/visual_bible.json")
CHAR_DESIGNS = os.path.expanduser("~/.agentic-os/character_designs/character_designs.json")

def read_json(p):
    with open(p) as f:
        return json.load(f)

def write_json(p, data):
    with open(p, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

# ── 109角色 98版演员及关键特征描述 ─────────────────────────────
# 格式: pinyin: (name, actor, facial_desc, costume, build_desc, vp2_scene, vp2_action)

CHAR_PROFILES = {
    "songjiang": ("宋江", "李雪健",
        "short stature, dark weathered face, thin eyebrows sinking into deep-set eyes, humble expression hiding a cunning and calculating mind",
        "dark green Song-dynasty official robe with black gauze cap and jade belt",
        "small thin civil-official build",
        "writing a revolutionary poem on the Xunyang Tower wall, drunk and impassioned",
        "He stands drunk before the Xunyang Tower wall, brush in hand, his humble mask slipping to reveal raw ambition and righteous fury. The ink flows from his brush as he writes his fate.")
    ,
    "lujunyi": ("卢俊义", "王卫国",
        "tall imposing figure, dignified square-jawed face, thick brows radiating righteousness, noble bearing with an air of natural authority",
        "exquisite wealthy landlord's brocade robe with a jade belt and silk headpiece",
        "tall, broad-shouldered, heroic build",
        "being captured on the Liangshan slopes, surrounded by heroes",
        "The wealthy Lu Junyi stands surrounded by Liangshan heroes, his silver spear held firm, his square-jawed face showing defiance and dignity even in capture.")
    ,
    "wuyong": ("吴用", "宁晓志",
        "lean scholarly frame, weather-beaten face with a long three-strand beard, deep calculating eyes, a scholar's pride mixed with a strategist's cunning",
        "plain greyish-white scholar's robe with a square soft cap, holding a feather fan",
        "lean, scholarly, unassuming build",
        "devising the scheme to steal the birthday gifts, pointing and giving orders in a grove",
        "The strategist Wu Yong stands hidden in a grove, his feather fan pointed forward, his long beard stirring in the wind as he coordinates the ambush.")
    ,
    "gongsunsheng": ("公孙胜", "汪永贵",
        "lean ascetic face, clear profound eyes with a transcendent gaze, a wispy goatee, Taoist sage aura",
        "grey Taoist robe with a Taoist crown, holding a horsetail whisk",
        "lean, ethereal, Taoist-priest build",
        "summoning a mystical wind in battle, Taoist robe flaring",
        "The Taoist sage Gongsun Sheng stands on a hillside, his grey robe swirling as he chants, his eyes glowing with mystical power and wild wind rising around him.")
    ,
    "guansheng": ("关胜", "李振起",
        "deep red face like a ripe jujube, long flowing beard, proud arched brows, imposing air of a legendary general",
        "green battle robe over gleaming golden armor, holding the Green Dragon Crescent Blade",
        "tall, imposing, warrior build",
        "charging into battle on horseback, Green Dragon Crescent Blade raised high",
        "Guan Sheng charges on his warhorse, his flowing beard whipping in the wind, the massive Crescent Blade raised high, gleaming in the sunlight.")
    ,
    "linchong": ("林冲", "周野芒",
        "refined scholarly face, proper features, restrained tragic eyes carrying deep sorrow and suppressed fury, thin mustache",
        "faded blue-grey cloth robe, felt hat with a wide brim, frayed cuffs hinting at past dignity",
        "lean, athletic, martial-artist build",
        "standing alone in the snowy mountain temple, spear in hand, snow falling around him",
        "Lin Chong stands alone in the ruined mountain temple, snow swirling through the broken roof, his spear held ready, his refined face a mask of cold fury and tragic resolve.")
    ,
    "qinming": ("秦明", "王文升",
        "fierce round face, bulging angry eyes, bristling full beard that stands on end, a face like thunder itself",
        "scale armor with a red-tasseled helmet over a red battle robe, wielding a wolf-tooth club",
        "stocky, powerfully built, aggressive warrior build",
        "charging into battle with berserk fury, wolf-tooth club swinging",
        "Qin Ming charges like a thunderbolt, both arms swinging the fearsome wolf-tooth club, his face twisted in battle fury, his beard bristling.")
    ,
    "huyanzhuo": ("呼延灼", "贾石头",
        "broad square face, long dignified beard, calm yet commanding eyes of a veteran general",
        "iron helmet and interlocking chainmail, twin steel maces in hand",
        "stocky, solid, general's build",
        "commanding from horseback, twin maces raised, chainmail glinting",
        "Huyan Zhuo sits firm on his horse, twin steel maces gleaming in the sun, his chainmail interlocking like scales, his expression the calm authority of a seasoned commander.")
    ,
    "huarong": ("花荣", "修庆",
        "handsome heroic face, sword-like brows and starry eyes, youthful sharp features radiating warrior spirit",
        "silver-white battle robe with a carved bow at the waist, light armor",
        "tall, graceful, young archer build",
        "drawing his bow to shoot a wild goose from a hundred paces, one eye squinted",
        "Hua Rong draws his longbow to its full arc, one eye squinted with perfect aim, his silver robe flowing in the wind like a banner.")
    ,
    "chaijin": ("柴进", "郑强",
        "fair smooth skin, short refined beard, noble aristocratic features, the easy grace of a man born to wealth",
        "embroidered brocade robe with a scholar's cap, a fine sword at his waist",
        "upright, elegant, aristocratic build",
        "entertaining guests in his lavish manor, raising a wine cup with a warm smile",
        "Chai Jin raises a jade wine cup in his grand manor hall, his refined face lit by lantern light, the picture of noble generosity.")
    ,
    "liying": ("李应", "未详",
        "sharp shrewd face, long goatee, steady calculating eyes, the composed air of a wealthy estate master",
        "dark well-tailored brocade robe with a jade belt and ornate cap",
        "solid, dignified, landowner's build",
        "standing on the watchtower of his estate, crossbow in hand, surveying his lands",
        "Li Ying stands on the high watchtower of the Li Family Estate, a steel crossbow resting beside him, his shrewd eyes scanning the horizon.")
    ,
    "zhutong": ("朱仝", "杨增元",
        "dark reddish jujube-colored face, a magnificent beard cascading to his chest, imposing yet loyal and kind eyes",
        "official constable's uniform over chainmail, a long saber at his waist",
        "tall, upright, imposing build",
        "releasing a wanted man discreetly on a dark road, his beard stirring in the night wind",
        "Zhu Tong stands on a desolate road under moonlight, his magnificent beard stirring, his saber sheathed, his eyes filled with a difficult decision between duty and honor.")
    ,
    "luzhishen": ("鲁智深", "臧金生",
        "extremely burly and stout, wide face and large ears, fierce intimidating face with a full bristling beard, yet eyes that are clear, wise, and serene, nine scars on his forehead from his monk's vows",
        "coarse grey monk's robe worn open at the chest, a large string of heavy wooden Buddhist beads around his neck",
        "massive, bear-like, muscular build",
        "uprooting a willow tree with his bare hands in front of the temple, muscles straining",
        "Lu Zhishen wraps his powerful arms around the trunk of a massive willow tree. With a mighty roar, the roots tear from the earth, dirt flying, his grey robe flapping, the beads swinging wildly around his neck.")
    ,
    "wusong": ("武松", "丁海峰",
        "thick ink-black eyebrows slanting up to his temples like drawn sabers, sharp phoenix eyes gleaming with intensity, a stern and imposing square-jawed face that inspires fear without anger",
        "grey headband monk's robe, the iconic iron fillet headband binding his forehead, simple cloth shoes",
        "tall, muscular, tiger-like build, broad shoulders and a narrow waist",
        "confronting a phalanx of armed guards in a blood-spattered hallway, saber dripping, his phoenix eyes burning with righteous fury",
        "Wu Song stands in the blood-soaked hallway of the Mandarin's mansion, his gleaming steel saber raised, his phoenix eyes blazing with cold fury and iron resolve.")
    ,
    "xuning": ("徐宁", "张巍",
        "proper upright face, composed steady gaze, the disciplined bearing of an imperial martial arts instructor",
        "polished iron helmet with a red plume, plum-blossom-etched chainmail over a blue robe, holding a golden spear",
        "steady, upright, instructor's build",
        "demonstrating the hook sickle spear technique in an imperial training yard",
        "Xu Ning demonstrates the famed hook-sickle spear technique in the training yard, his form perfect, his expression the quiet pride of a man who knows his craft.")
    ,
    "suochao": ("索超", "张浩",
        "round face, large ears, wide mouth with a full bristling beard, urgent fierce eyes, a man always ready to charge",
        "bronze scale armor with a bright red cloak, wielding a golden battle-axe",
        "stocky, solid, forward-charge build",
        "thundering ahead of the army on horseback, golden axe raised, mouth open in a battle cry",
        "Suo Chao thunders forward at the head of the vanguard, his golden axe raised high, his battle cry echoing across the field, his red cloak streaming behind him.")
    ,
    "daizong": ("戴宗", "王基明",
        "lean wiry frame, gaunt alert face, sharp watchful eyes, the look of a man who travels endlessly",
        "dark short-cut traveling clothes, magical talismans tied around his calves, a wide-brimmed hat",
        "lean, long-legged, courier build",
        "running across a misty mountain path at supernatural speed, talismans glowing",
        "Dai Zong races across a winding mountain path, his legs a blur of motion, the talismans on his calves humming with power, dust trailing behind him like a ghost.")
    ,
    "liutang": ("刘唐", "邰祖辉",
        "fierce ugly face, high jutting cheekbones, a prominent red birthmark beside his temple covered in black-yellow hair, ruthless eyes",
        "tattered animal-hide vest over bare torso, a coarse rope belt, a simple blade at his hip",
        "burly, rough, outlaw build",
        "emerging from the grass to intercept a messenger on a lonely road",
        "Liu Tang bursts from the tall grass onto a lonely road, his face fierce, the red birthmark vivid against his skin, his blade already half-drawn.")
    ,
    "shijin": ("史进", "郭军",
        "round silver-pan face, fair skin, young bright eyes full of fierce spirit, nine dragon tattoos curling across his chest and arms",
        "martial outfit tied loosely at the chest, exposing the full-body dragon tattoos, simple cloth trousers",
        "tall, athletic, young martial-artist build",
        "practicing the staff in the moonlight, his dragon tattoos glistening with sweat",
        "Shi Jin whirls his staff under the moonlight, his muscles gleaming, the nine dragons tattooed on his torso seeming to writhe and dance with each movement.")
    ,
    "muhong": ("穆弘", "未详",
        "broad open face, bold untamed beard, fierce confident eyes, the arrogant swagger of a local tyrant",
        "splendid embroidered robe under a flowing cloak, an ornate sword at his waist",
        "tall, bold, local-chieftain build",
        "standing on the pier of Jieyang, arms crossed, surveying his territory",
        "Mu Hong stands on the Jieyang pier, his cloak rippling in the river wind, his bold face wearing the arrogant smile of a man who owns the waterfront.")
    ,
    "leiheng": ("雷横", "郭柏松",
        "purplish-black face, fan-shaped whiskers spreading outward, arrogant dignified eyes, the pride of a county constable",
        "felt hat and official constable's uniform, a heavy-bladed saber at his belt",
        "solid, stout, officer's build",
        "patrolling the streets of Yuncheng County, hand on his saber hilt",
        "Sergeant Lei Heng patrols the market streets of Yuncheng, his fan-shaped whiskers bristling, his hand resting on his saber, a figure of local authority.")
    ,
    "likui": ("李逵", "赵小锐",
        "dark black skin like iron, face of ferocious flesh, bristling hair and beard like a wild beast, round bulging eyes that switch between murderous rage and childlike innocence",
        "rough dark fabric vest, bare muscular arms, a pair of massive battle-axes hanging at his waist",
        "massive, iron-tower-like build, bulging chest muscles, a body built for pure destruction",
        "killing four tigers on Yiling Ridge with his bare hands and a short blade, blood on his face and tears in his eyes",
        "Li Kui stands over the four dead tigers, blood dripping from his hands, his fierce round eyes both savage and strangely innocent as he mourns his mother.")
    ,
    "lijun": ("李俊", "杨宝光",
        "dark sun-weathered skin, thick eyebrows over deep-set shrewd eyes, the face of a man who has sailed every river",
        "coarse hemp shirt tied at the waist, trousers rolled to the knee, a boat oar beside him",
        "solid, strong, river-boatman build",
        "steering a boat through the rapids, barefoot on the deck, eyes fixed on the swirling water",
        "Li Jun stands barefoot on the prow of his boat, muscling the steering oar through the churning rapids, his dark face a mask of concentration.")
    ,
    "ruanxiaoer": ("阮小二", "刘卫华",
        "sallow waxy complexion, deep weathered wrinkles like river sand, weary yet determined eyes, the face of a man who has fished every day of his life",
        "straw rain cape over a tattered blue shirt, a bamboo hat pushed back, hemp trousers",
        "lean, sinewy, fisherman's build",
        "casting a heavy net into the Liangshan Marsh from a small boat",
        "Ruan the Second casts his net wide over the misty Liangshan Marsh, his sinewy frame coiling with each throw, the weathered face of a true waterman.")
    ,
    "zhangheng": ("张横", "兰恭英",
        "dark skin, full thick beard, fierce cruel mouth twisted in a constant sneer, shark-like eyes",
        "dark boatman's jacket open at the chest, a hooked spear resting against his shoulder",
        "burly, fierce, river-pirate build",
        "standing at the prow of a boat on the Xunyang River, hook-spear ready",
        "Zhang Heng stands at the prow of his boat, the Xunyang River mist swirling around him, his hooked spear gleaming, his sneer promising danger to any passenger.")
    ,
    "ruanxiaowu": ("阮小五", "张衡平",
        "gloomy gaunt face, a prominent green birthmark on his cheek, solitary brooding eyes that have seen too much hardship",
        "same coarse fishermen's clothes as his brothers, a length of rope at his waist, sleeves torn",
        "lean, wiry, brooding fisherman build",
        "sitting silently on the bank of the marsh, carving a piece of wood with a small knife",
        "Ruan the Fifth sits alone on the marshy bank, carving wood with idle violence, his green-marked cheek turned away, a man whose silence speaks louder than shouts.")
    ,
    "zhangshun": ("张顺", "张亚坤",
        "strikingly snow-white skin, delicate handsome face with refined features, clear lively eyes like still water, a free and easy smile",
        "light white linen shirt, open at the collar, barefoot, no weapons visible, trusting the water itself",
        "tall, lean, sleek, swimmer's build with smooth streamlined muscles",
        "surfacing from the depths of a clear river like a white spirit, water cascading from his shoulders",
        "Zhang Shun breaks the surface of the river, water streaming from his white skin, his clear eyes bright, a fish in his hand and a confident smile on his lips.")
    ,
    "ruanxiaoqi": ("阮小七", "李冬果",
        "sallow complexion, small but sharp restless eyes, a wild untamed spirit visible in every expression, wolfish grin",
        "worn blue hemp shirt tied with grass rope, straw sandals, a small knife tucked into his belt",
        "lean, wiry, wild-fisherman build",
        "laughing carelessly from the prow of a boat, a gourd of wine in hand",
        "Ruan the Seventh tips his wine gourd back and laughs into the wind, his wild eyes squinting against the sun, the very picture of untamable freedom.")
    ,
    "yangxiong": ("杨雄", "陈之辉",
        "sallow pale complexion, short neat mustache, silent melancholy eyes, the weary face of a man burdened by his own life",
        "black gauze prison officer's uniform, a ring of keys at his belt, simple dark cap",
        "lean, quiet, jailer's build",
        "discovering his wife's betrayal, his face frozen in shock and fury outside his own home",
        "Yang Xiong stands frozen in the shadows of his own courtyard, his sallow face draining of color, the truth dawning with crushing weight in his eyes.")
    ,
    "shixiu": ("石秀", "杨凡",
        "delicate handsome features belying a core of cold steel, eyes that flicker between calm and lethal, a face ready to fight to the death at any moment",
        "tight black martial outfit with dark wrappings from calf to foot, a long-bladed Pudao sheathed across his back",
        "wiry, compact, assassin's build",
        "leaping from a rooftop, blade drawn, to ambush a foe below",
        "Shi Xiu drops from the rooftop without a sound, his black figure a blur against the night, his blade already whistling through the air before his feet touch ground.")
    ,
    "xiezhen": ("解珍", "孔庆元",
        "dark sun-beaten skin, lean angular face, eagle-sharp eyes that miss nothing in the forest, the quiet intensity of a hunter",
        "tiger-skin vest over bare torso, leather arm guards, a steel hunting fork strapped to his back",
        "lean, agile, hunter's build",
        "tracking a wounded tiger through deep forest, crouched low, steel fork ready",
        "Xie Zhen crouches in the forest gloom, tracking blood-spoor with the patience of a true hunter, his steel fork gleaming in a shaft of light.")
    ,
    "jiebao": ("解宝", "韩福利",
        "similar to his brother but with darker, more venomous eyes, the coiled-spring tension of a man who strikes without warning",
        "matching tiger-skin vest and leather gear, twin short blades at his waist",
        "lean, coiled, predatory build",
        "emerging silently from thick brush behind his brother, covering the escape route",
        "Xie Bao materializes from the brush without a sound, twin blades already half-drawn, his venomous eyes scanning their surroundings while his brother tracks the prey.")
    ,
    "yanqing": ("燕青", "王光辉",
        "exquisitely handsome face with jade-white skin, lips like cinnabar, bright star-like eyes, delicate refined features with a roguish twinkle, an intelligent and nimble expression",
        "embroidered brocade robe with intricate patterns, a small repeating crossbow hidden inside his sleeve, a floral pin in his hair",
        "graceful, lithe, acrobat's build",
        "defeating the prodigious wrestler Ren Yuan atop the ceremonial platform at Taiyuan Temple, a crowd roaring below",
        "Yan Qing twists mid-air, his body a perfect arc, redirecting the massive wrestler's momentum with impossible grace, the crowd gasping as the giant crashes to the platform.")
    ,
    "zhuwu": ("朱武", "由利平",
        "goatee beard, deep narrow eyes always slightly squinting as if calculating, the arcane air of a Taoist strategist",
        "grey Taoist robe with a simple cloth belt, a feather fan in hand, a round cap",
        "lean, scholarly, strategist build",
        "standing before a sand-table map, pointing with his feather fan at troop formations",
        "Zhu Wu studies the sand-table map, his feather fan tracing the path of an advancing army, his squinting eyes reading three moves ahead.")
    ,
    "huangxin": ("黄信", "未详",
        "fierce intimidating face, full bristling beard, arrogant eyes that look down on all outlaws",
        "brass helmet and iron armor over a red uniform tunic, a large executioner's sword at his waist",
        "stocky, imposing, warrior build",
        "riding patrol with sword drawn, a phalanx of troops at his back",
        "Huang Xin rides at the head of a column of government soldiers, his executioner's sword drawn, his fierce gaze sweeping the ridges for any sign of bandits.")
    ,
    "sunli": ("孙立", "齐景斌",
        "pale yellowish complexion, long elegant beard, melancholy eyes with hidden sharpness, the 'Sick' commander's deceptive calm",
        "bronze helmet over dark leather armor, a steel mace at his side, a dark military coat",
        "lean, steady, officer's build",
        "standing at the city gate, opening it to a trusted colleague — a decisive moment of betrayal or loyalty",
        "Sun Li stands at the city gate, his hand on the iron release, his pale face unreadable, the weight of a life-changing decision in his melancholy eyes.")
    ,
    "xuanzan": ("宣赞", "未详",
        "ugly face as dark as a pot-bottom, upturned nostrils, wild curly hair and a curly beard, but a determined warrior's spirit",
        "bright red military robe over golden scale armor, a curved steel saber",
        "sturdy, powerful, ugly-majestic build",
        "holding the line alone against multiple foes on a narrow bridge, his ugly face fierce",
        "Xuan Zan holds the narrow bridge alone, his saber flashing, his dark ugly face twisted in a ferocious grin as he drives back wave after wave of attackers.")
    ,
    "haosiwen": ("郝思文", "未详",
        "proper rectangular face, stubborn eyes that refuse to yield even when outmatched, the face of a loyal officer",
        "iron helmet and boiled-leather armor, a long spear in hand",
        "upright, solid, officer's build",
        "fighting to the last on the battlefield surrounded, spear shattered, drawing his sword",
        "Hao Siwen stands surrounded, his spear broken, drawing his long sword with steady hands, his stubborn eyes showing no trace of surrender.")
    ,
    "hantao": ("韩滔", "甄力强",
        "composed square face, short confident mustache, steady experienced eyes of a veteran officer",
        "iron helmet and interlocking chainmail, a jujube-wood lance, a dark cavalry cloak",
        "compact, solid, veteran officer build",
        "leading a cavalry charge, lance lowered, cloak streaming behind",
        "Han Tao leads the charge, his lance couched and steady, his veteran's eyes picking his target, his dark cloak streaming like a war banner behind him.")
    ,
    "pengqi": ("彭玘", "王春辉",
        "majestic face, thick eyebrows, sharp piercing eyes, the fierce brow of a heavenly general",
        "phoenix-wing golden helmet, golden chainmail armor, wielding a three-pointed double-edged blade",
        "tall, stately, general's build",
        "pausing mid-battle, his three-pointed blade raised, surveying the field with commander's eyes",
        "Peng Qi sits tall on his horse, the phoenix-wings of his helmet gleaming, his three-pointed blade held high as he commands the battlefield with a general's calm.")
    ,
    "shantinggui": ("单廷珪", "未详",
        "sinister gaunt face, short forked beard, cunning treacherous eyes, the calculating look of a water-warfare expert",
        "black lacquered helmet and dark battle robe with water-resistant leather armor",
        "lean, cunning, water-commander build",
        "directing a river-crossing ambush from a command boat, signaling with signal flags",
        "Shan Tinggui signals from his command boat, his dark-clad figure silhouetted against the river mist, directing a trap on the water with silent hand gestures.")
    ,
    "weidingguo": ("魏定国", "未详",
        "flushed red face, full beard, explosive violent eyes, a man who brings fire to every fight",
        "red copper helmet and vermilion battle robe, fire-starting equipment strapped to his back",
        "stocky, explosive, fire-commander build",
        "hurling a fire bomb from horseback, the explosion lighting up his red face",
        "Wei Dingguo hurls a clay fire-bomb, the explosion illuminating his crimson face, his red armor glowing like embers in the heat.")
    ,
    "xiaorang": ("萧让", "未详",
        "refined delicate face, elegant scholarly gaze, the pure bookishness of a master calligrapher",
        "white scholar's robe with a square cap, a brush tucked into his belt, scrolls under his arm",
        "lean, delicate, scholar's build",
        "writing a forged letter with perfect brush strokes, his sleeves brushing the table",
        "Xiao Rang sets brush to paper with perfect elegance, his letter so convincing it could fool a general—the power of the brush in his steady hand.")
    ,
    "peixuan": ("裴宣", "未详",
        "stern upright face, thin stern lips, the incorruptible gaze of a judge, worn by years of enforcing the law",
        "dark official's robe with a magistrate's cap, a wooden gavel tucked into his sash",
        "lean, upright, judge's build",
        "presiding over a court of justice in the mountain stronghold, gavel in hand",
        "Pei Xuan sits in the Hall of Justice, his gavel raised, his stern face a monument to fairness — even bandits under his judgment respect him.")
    ,
    "oupeng": ("欧鹏", "未详",
        "hardened face, brows perpetually knitted, the scarred and weathered look of a career soldier turned outlaw",
        "worn military armor over a faded tunic, a heavy broadsword, a scar visible on his forearm",
        "compact, hard, soldier's build",
        "training new recruits in the stronghold, demonstrating a sword form with old-soldier patience",
        "Oupeng drills recruits in the stronghold yard, his weathered face showing patience, correcting each stance with the calm of a man who has survived countless battles.")
    ,
    "dengfei": ("邓飞", "未详",
        "ruddy round face, wild tangled brows, fierce loyal eyes that spark with righteous anger",
        "worn leather armor over a dark tunic, a chain-linked meteor hammer at his side",
        "stocky, strong, loyal-fighter build",
        "fighting fiercely in close quarters, his meteor hammer whistling in a deadly arc",
        "Deng Fei whips his meteor hammer in a deadly arc, his round face red with exertion, a loyal warrior fighting with everything he has.")
    ,
    "yanshun": ("燕顺", "未详",
        "coarse rugged face, full wild whiskers, the red-rimmed eyes of a man whose temper flares easily",
        "tiger-skin cloak over rough robes, a large broad saber on his back",
        "sturdy, rough-mannered, mountain-brigand build",
        "standing at the entrance of his mountain lair, broad saber drawn, glaring down at approaching riders",
        "Yan Shun stands at the gate of his mountain lair, the tiger-skin cloak over his shoulders giving him the look of a great cat, glaring at intruders with undisguised hostility.")
    ,
    "yanglin": ("杨林", "未详",
        "lean hard face, thin foxy eyes always darting, the calculating look of a career messenger and spy",
        "plain grey traveler's clothes, a wide sash concealing a short blade, a pack on his back",
        "lean, quick, scout's build",
        "scouting an enemy camp from a high ridge at dusk, taking notes on parchment",
        "Yang Lin crouches on a high ridge, his quick eyes scanning the enemy camp below, making mental notes of every detail, a phantom on the mountain.")
    ,
    "lingzhen": ("凌振", "未详",
        "soot-smudged face, intense obsessive eyes, the distracted focus of a man who lives inside his own inventions",
        "heavy leather apron over a simple tunic, hands stained black with gunpowder, tools hanging from his belt",
        "sturdy, heavy-armed, engineer's build",
        "adjusting the angle of a large cannon on the mountaintop fortress ramparts",
        "Ling Zhen crouches beside his great cannon, adjusting the elevation with quiet concentration, his soot-smeared face alight with the joy of creation.")
    ,
    "jiangjing": ("蒋敬", "未详",
        "thin ascetic face, wire-rimmed scholar's eyes, the meticulous precision of a born accountant",
        "plain grey robe with sleeves tied up for work, an abacus never far from his hand",
        "lean, precise, accountant's build",
        "reviewing ledgers in the Liangshan storehouse, abacus clicking steadily under his fingers",
        "Jiang Jing runs his abacus with practiced speed, his thin face bent over the ledgers, every coin accounted for in the mountain stronghold's treasury.")
    ,
    "lvfang": ("吕方", "未详",
        "young fair face, bright eager eyes under arched brows, a cocky confident smirk of youth",
        "bright red military robe with colorful armor, carrying a square-painted halberd",
        "tall, youthful, eager-warrior build",
        "practicing with his halberd, each strike precise and showy",
        "Lu Fang whirls his painted halberd in a glittering arc, each move practiced to perfection, the bright confidence of youth in every flourish.")
    ,
    "guosheng": ("郭盛", "未详",
        "young fair face similar to Lu Fang, but with steadier less flamboyant eyes, a more focused young warrior",
        "white military robe with silver-edged armor, carrying a square-painted halberd",
        "tall, steady, young-warrior build",
        "riding alongside Lu Fang in formation, halberds crossed in a ceremonial guard",
        "Guo Sheng rides beside Lu Fang, the two halberds crossed in a perfect V, their matching armor gleaming in the sunlight.")
    ,
    "andaoquan": ("安道全", "未详",
        "kind scholarly face, gentle wise eyes, the weathered hands and compassionate gaze of a healer",
        "plain scholar's robe, a medicine box slung across his shoulder, herb pouches at his belt",
        "lean, gentle, healer's build",
        "treating a wounded warrior in a torch-lit cave, hands steady as he sets a broken bone",
        "An Daoquan's steady hands work by torchlight, setting a warrior's broken bone, his kind face a beacon of calm in the pain-filled cave.")
    ,
    "huangfuduan": ("皇甫端", "未详",
        "ruddy outdoorsman's face, purple curling beard around his jaw, the knowing eyes of a man who speaks to horses",
        "dusty leather jerkin over coarse cloth, grooming tools at his belt, horsehair bracelets",
        "stocky, stocky, horse-doctor build",
        "calming a spooked warhorse with a gentle hand on its muzzle",
        "Huangfu Duan murmurs softly to a panicked warhorse, his hand steady on its muzzle, the great beast quieting under his touch, a true horse-whisperer.")
    ,
    "wangying": ("王英", "未详",
        "short dwarf-like stature, coarse ugly face, lecherous narrow eyes always roaming, a shameless grin",
        "worn mismatched armor pieces, a large saber too big for his frame dragging at his hip",
        "short, stocky, misshapen build",
        "scrambling on horseback despite his short legs, calling crude taunts at the enemy",
        "Wang Ying rides his too-large horse with comical determination, his ugly face twisted in a shout of defiance, raising his oversized saber.")
    ,
    "husanniang": ("扈三娘", "郑爽",
        "strikingly beautiful face with pale jade skin, a high heroic brow over sharp almond eyes, cold aloof temperament that warns all who approach, a woman of steel in a flower's guise",
        "floral headdress over a golden chainmail vest, a flowing red cape, twin crescent-blade sabers in hand",
        "tall, graceful yet athletic, warrior-woman build",
        "riding into battle swift as the wind, her two crescent- moon blades whistling past her horse's ears",
        "Hu Sanniang rides like the wind into battle, twin crescent-blade sabers glinting on either side of her, her cold beautiful face the last thing her enemies see.")
    ,
    "baoxu": ("鲍旭", "未详",
        "gaunt skull-like face with hollow cheeks, sharp protruding teeth, dark sunken eyes that seem to glow with relish for battle",
        "dark armor with spikes on the shoulders, a heavy broadsword held in both hands",
        "tall, skeletal, deathly build",
        "bursting through the enemy line with his broadsword swinging, a grim reaper on foot",
        "Bao Xu charges, his grim reaper's face split in a skull-like grin, his massive broadsword cleaving through the fray.")
    ,
    "fanrui": ("樊瑞", "未详",
        "wild unkempt face, intense manic eyes, a twisted mix of Taoist mysticism and outlaw brutality",
        "dark frayed Taoist robe with strange symbols embroidered on it, a short staff topped with a skull",
        "tall, gaunt, sinister build",
        "chanting an incantation in a clearing, dark wind swirling leaves around him as he summons a storm",
        "Fan Rui raises his skull-topped staff to the darkening sky, his wild hair whipping in the unnatural wind he has summoned, demonic energy crackling around him.")
    ,
    "kongming": ("孔明", "未详",
        "young coarse face, thick heavy brows, stubborn rebellious eyes, the face of a small-town bully given power",
        "rough leather armor over simple cloth, a crude iron spear",
        "stocky, rough, small-time bully build",
        "strutting in the streets of White Tiger Village with his brother, chest puffed out",
        "Kong Ming struts through his hometown with his